### ISSUE TITLE
ComfyUI hardcoded "3" key causes "Key Error" if the key changes

### ISSUE THREAD

**Issue by coreyryanhanson** [zanllp/sd-webui-infinite-image-browsing#355]
I love that this extension is able to read the metadata from ComfyUI exports, however on light modifications to the default nodes, the extension will fail  at reading the metadata from a "KeyError"

The bug occurs on this line:
https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/da9fbe162a923e971f8877a7a0929ecfdc93082f/scripts/iib/tool.py#L309C1-L310C1
Because it expects the key to be "3".

The problem is that some of my outputs have the key as "4" (and I imagine the actual prompt may increment even further)

I am not familiar with the outputs of ComfyUI enough to determine what causes this behavior and if this is certain to be intended behavior from their API.

I do know that the bug was easily reproducible on my system by starting with the default layout, changing the model to a 2.1 checkpoint (and also increasing dimensions to 768x768), and replacing the KSampler node with the KSampler (Advanced Node).

**Comment by zanllp** [comment]
In the latest version, I have fixed this issue and it will attempt to acquire KSampler from key “3”. In fact, the support for ComfyUI in IIB is limited and it is still an experimental feature. I haven't even mentioned this feature in the README. If you're interested, you can check our previous discussion #202.

**Comment by coreyryanhanson** [comment]
Makes sense. I noticed this feature is very new. I just saw the change. And while a definite improvement it didn't fix the problem if the node was the advanced version of the KSampler.
I just made a light edit into a pull request here that fixed the problem for me:
https://github.com/zanllp/sd-webui-infinite-image-browsing/pull/359

**Comment by zanllp** [comment]
oops, looks like I missed some of the information you provided 😲

**Comment by zanllp** [comment]
The branch has already been merged.

**Comment by coreyryanhanson** [comment]
Awesome! Thanks!
